spring:
  application:
    name: bottle-api-gateway
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: ${bottle.configServer.serviceId} 
      username: ${bottle.configServer.username} 
      password: ${bottle.configServer.password} 
      uri: 'http://${bottle.configServer.username}:${bottle.configServer.password}@${bottle.configServer.host}:8888' 

bottle:
  configServer:
    serviceId: ${SPRING_CLOUD_CONFIG_DISCOVERY_SERVICE_ID:config-server}
    username: ${CONFIG_SERVER_USERNAME:configserver}
    password: ${CONFIG_SERVER_PASSWORD:1234567}
    host: ${CONFIG_SERVER_HOST:localhost}
  serviceRegistry:
    username: ${SERVICE_REGISTRY_USERNAME:serviceregistry}
    password: ${SERVICE_REGISTRY_PASSWORD:1234567}
    defaultZoneHost: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:localhost}

eureka:
  client:
    service-url:
      defaultZone: 'http://${bottle.serviceRegistry.username}:${bottle.serviceRegistry.password}@${bottle.serviceRegistry.defaultZoneHost}:8761/eureka'
  instance:
    hostname: ${bottle.serviceRegistry.defaultZoneHost}
  
