server:
  port: 8081
  servlet:
    context-path: '/bottle-authuser/'

spring:
  application:
    name: bottle-authuser-service
  data:
    mongodb:
      uri: mongodb://${bottle.mongodb.username}:${bottle.mongodb.password}@${bottle.mongodb.name}:27017/bottle
#   kafka:
#     bootstrap-servers: '${bottle.kafka.name}:${bottle.kafka.port}'
  output:
    ansi:
      enabled: always

bottle:
#   kafka:
#     name: ${KAFKA_NAME:localhost}
#     port: ${KAFKA_PORT:29092}
  mongodb:
    name: ${MONGODB_NAME:localhost}
    username: ${MONGODB_USERNAME:admin}
    password: ${MONGODB_PASSWORD:123456}